### ISSUE TITLE
On/Off switch would be nice

### ISSUE THREAD

**Issue by mlisitski** [tilmanginzel/alfred-bluetooth-workflow#1]
Could you add On and Off states (to save battery when no need for BT).

**Comment by tilmanginzel** [comment]
Hi @mlisitski, yes that is a good idea. Currently `blt {device}` is used to (de)select a device. What would you recommend for the on/off switch? Maybe `blt-toggle`? Or explicitly `blt-on`/`blt-off`? I will try to find some time for this on the weekend.

**Comment by mlisitski** [comment]
If you could do both to change state, this would be a hit for BT Alfred workflow. I did search and could not find any workflow that toggle state and allows to connect devices at the same time):
blt-toggle - invert current state.
blt-on/blt-off - switch state.

**Comment by tilmanginzel** [comment]
Good idea, supporting both `blt-toggle` and `blt-on/off` should be the best approach. :)

**Comment by tilmanginzel** [comment]
Hey @mlisitski, I have added the commands to the latest [release](https://github.com/tilmanginzel/alfred-bluetooth-workflow/releases/tag/v0.2.0). Feel free to give it a try, would be great to know if it works for you! :)

**Comment by mlisitski** [comment]
Thanks, works. But, for some reason, I can use only "blt-". Surprisingly, it is even better as less typing ;)

**Comment by tilmanginzel** [comment]
Thanks for checking! Just to make sure that I understand you correctly: Do you mean by only using `blt-` that you select the specific entry afterwords via keyboard/mouse/shortcut? 

While I agree that this is much faster than to type the full command, there is still a minor usability issue: Currently, when you type `blt-on`, `blt-off` or `blt-toggle` the command is executed _immediately_, without the need to press enter. From a user perspective this is really weird and annoying, so I still have to find a solution for this. I will keep digging in a few days maybe. ;)

**Comment by mlisitski** [comment]
> Thanks for checking! Just to make sure that I understand you correctly: Do you mean by only using `blt-` that you select the specific entry afterwords via keyboard/mouse/shortcut?
Yes.
When I type blt-on, blt-off or blt-toggle it opens google and not a command.
Also, blt-toggle could be switched to blt-t (faster)

**Comment by tilmanginzel** [comment]
> blt-toggle could be switched to blt-t

Good idea, I will keep this in mind for the next release.

> When I type blt-on, blt-off or blt-toggle it opens google and not a command.

If you press enter quite fast, Google opens. But the command is still executed. As I mentioned, the commands executes immediately as soon as its typed (without pressing enter), the command then disappears and Google Search is pre-selected.

I will look into this, as it's pretty annoying.

**Comment by tilmanginzel** [comment]
@mlisitski I will close this issue now as `blt-on`, `blt-off` and `blt-toggle` commands are implemented. The usability issue mentioned above is also fixed in v0.4.0.
