### ISSUE TITLE
Latest 0.5.0 causes etree.so errors

### ISSUE THREAD

**Issue by avxkim** [tilmanginzel/alfred-bluetooth-workflow#11]
When using an older version, i have no issues under Catalina, but 0.5.0 gives such error about `etree.so` from unidentified developer.

I also have this issue with airpods: https://github.com/tilmanginzel/alfred-bluetooth-workflow/issues/10

**Comment by tilmanginzel** [comment]
Hi, #10 was just fixed. :) Will close this as duplicate of #9 and comment there regarding Catalina.
