### ISSUE TITLE
Add script to restart bluetooth

### ISSUE THREAD

**Issue by jdbruijn** [tilmanginzel/alfred-bluetooth-workflow#18]
Would you accept a PR to add a script/command to restart the bluetooth controller? The suggested command for this would be `blt-restart` and `Bluetooth: Restart`. I'd be happy to PR this, but thought first to check whether you'd accept something like this before spending the work on it.

I've got a very similar workflow to this one, https://github.com/vidavidorra/alfred-bluetooth-control, but haven't updated that in a very long time. In the meantime other similar workflows were built and this one looks nice! I want to archive my workflow, and possibly reference users to this one, but am missing this feature, which I use quite often.

**Comment by tilmanginzel** [comment]
Hey @jdbruijn, yes I would happily accept that PR. :) Sounds like a good extension to the workflow 👍
