### ISSUE TITLE
Icon transparency

### ISSUE THREAD

**Issue by BenjaminVanRyseghem** [tilmanginzel/alfred-bluetooth-workflow#23]
Hi!

First of all, thanks for the workflow, it's awesome!

I open this ticket because I use a dark theme alfred, and the gliph of the icon is transparent, which results in a not so nice UI

<img width="57" alt="Screen Shot 2021-04-22 at 09 32 16" src="https://user-images.githubusercontent.com/407891/115675041-88a19700-a34e-11eb-8442-e43f4089d398.png">

So I quickly hacked the `icons/*.png` files to color the glyph

<img width="48" alt="Screen Shot 2021-04-22 at 09 39 01" src="https://user-images.githubusercontent.com/407891/115675193-ab33b000-a34e-11eb-962b-60800540bc76.png">

Here are the files if needed:

![bluetooth-connected](https://user-images.githubusercontent.com/407891/115675743-2b5a1580-a34f-11eb-9347-49cc2d313653.png)
![bluetooth-disconnected](https://user-images.githubusercontent.com/407891/115675750-2bf2ac00-a34f-11eb-9fcf-7c27ed30500f.png)

I was thinking of greying a bit the "disconnected" one, will see 😃

**Comment by tilmanginzel** [comment]
Hi @BenjaminVanRyseghem, thanks for this idea! I'll add your icons in a new update soon. But I will probably stick with the color for now, to stay true to _Blue_ tooth. :)

**Comment by BenjaminVanRyseghem** [comment]
> to stay true to Blue tooth. :)

I was talking about the white rune, that I was considering greying instead of pure white to reflect the disconnect state :smile:

**Comment by tilmanginzel** [comment]
Oh, I see. I will probably stick with white glyphs for now, but luckily customizing this is very easy with Alfred workflows. :)

**Comment by tilmanginzel** [comment]
@BenjaminVanRyseghem I just published version 0.10.0 with your icons, thanks again!
