### ISSUE TITLE
Suggestion: use bluetooth user customised device names

### ISSUE THREAD

**Issue by a-rock-lobster** [tilmanginzel/alfred-bluetooth-workflow#24]
Hiya, 

I have a suggestion if I may. 

Mac OS gives the user the ability to change the display names of bluetooth devices. If one connects to alot of devices it's quite helpful for keeping track of what's what. 

A record of bluetooth device custom names can be found within:
/Library/Preferences/com.apple.Bluetooth.plist   

I would personally find it really helpful for quickly searching a device if the workflow reflected any user custom names. 

Best wishes,

Haydn

**Comment by tilmanginzel** [comment]
Hi @a-rock-lobster :) 

I somehow thought this was already working, as I saw in the past that some of my custom names have been reflected. So I did a quick test and observed the following:
- custom names seem to work for apple devices (magic mouse / keyboard), but they are only reflected after a reconnect
- custom names for third party devices were not shown

This workflow is using [blueutil](https://github.com/toy/blueutil) for all bluetooth commands, so I checked and found this issue: https://github.com/toy/blueutil/issues/40
I guess it makes sense to wait for that one and incorporate it afterwards here.

Cheers!

**Comment by VTrngNghia** [comment]
Hi

I'm using a non-Apple device (Galaxy Buds), and customized names worked well for me today.

**Comment by a-rock-lobster** [comment]
Hullo again,

Customised names have started working for me too. I guess this can be closed? 

Cheers,

**Comment by tilmanginzel** [comment]
Hi, thanks for the info. :) Seems to be working for me too now. If anyone encounters this issue again, feel free to reopen / leave a comment.
