### ISSUE TITLE
the new compiled blueutil is only compatible on M1 soc?

### ISSUE THREAD

**Issue by kopinions** [tilmanginzel/alfred-bluetooth-workflow#28]

**Comment by hoanghua** [comment]
Upgrading to version 0.11.1 fixes the issue "Bad CPU type in executable" for me. The workflow is back to normal now.

**Comment by tilmanginzel** [comment]
Hi @kopinions, @hoanghua, yes. Version 0.11.1 fixed the issue, see #26 #27.

**Comment by spearkkk** [comment]
<img width="478" alt="Screen Shot 2022-10-09 at 19 58 59" src="https://user-images.githubusercontent.com/19977962/194753075-82856849-60b8-4b97-b495-ebfd10a225fe.png">
<img width="718" alt="Screen Shot 2022-10-09 at 19 58 55" src="https://user-images.githubusercontent.com/19977962/194753077-2913b547-7b36-4ce9-9639-51bbce49e50c.png">


@tilmanginzel Hi, 
I got the same error, Could you check for this?
Thank you!

**Comment by tilmanginzel** [comment]
Hi @spearkkk, that is strange. Are you on M1 or Intel CPU? The blueutil binary was compiled on Intel, so it should also work on M1 with Rosetta.

**Comment by spearkkk** [comment]
@tilmanginzel  I used M2 and i didnt install Rosetta.
Could I need to install Rosetta?

**Comment by tilmanginzel** [comment]
@spearkkk Ah I see, then that's the root cause. I guess you have two options now:

1. Install Rosetta, or if you don't want to do that
2. [Compile a blueutil binary](https://github.com/toy/blueutil#from-source) on your laptop and replace it in the workflow folder

**Comment by spearkkk** [comment]
@tilmanginzel Thank you! I fixed it. :D
