### ISSUE TITLE
[error] Not able to import

### ISSUE THREAD

**Issue by im-AMS** [tilmanginzel/alfred-bluetooth-workflow#29]
```
Oops, unable to import!
The workflow you are trying to import
is invalid.
```
Device MacAir M1 BS 11.6

**Comment by tilmanginzel** [comment]
Hey @im-AMS, hm that's weird. Which Alfred version are you using?

I googled a bit and it seems that your file might be corrupted or you imported the wrong file(s). How did you install the workflow? Have you by any chance unpacked the [Bluetooth.Connector.alfredworkflow](https://github.com/tilmanginzel/alfred-bluetooth-workflow/releases/tag/v0.11.1) file? `.alfredworkflow` files are simply `.zip` files with a different extension, but they should not be unpacked prior importing.

**Comment by im-AMS** [comment]
after a lot of googling around i found just dragging the file to workflow did the trick. I guess its issue with alfred. Turns out it errors out irrespective of workflow file.
