### ISSUE TITLE
Error 86

### ISSUE THREAD

**Issue by charliesabino** [tilmanginzel/alfred-bluetooth-workflow#31]
Hi,

When trying to set up the workflow on my new MacBook Pro (M1), I'm getting this error message:

<img width="548" alt="CleanShot 2022-01-30 at 15 05 15@2x" src="https://user-images.githubusercontent.com/94320712/151717787-ec609325-6537-4a29-ae29-8700fc8d4356.png">

How do I fix this? 

Thanks.

**Comment by tilmanginzel** [comment]
Hi @charliesabino, sorry missed this one. Seems to be resolved, if it reoccurs, just reopen the issue.
