### ISSUE TITLE
Error preventing devices from showing up

### ISSUE THREAD

**Issue by austschn** [tilmanginzel/alfred-bluetooth-workflow#34]
I love this app and use it many times per day. Recently, it has stopped showing the devices available to connect to or disconnect from. I have tried to troubleshoot this on my own but have limited knowledge with what is brought up in the error message below. I have fully uninstalled and re-installed the workflow with version 0.12.0.

Here is what it looks like for me. Any help would be much appreciated!

Apple M1 Max
Monterey 12.4

<img width="560" alt="Screen Shot 2022-06-26 at 13 38 48" src="https://user-images.githubusercontent.com/61292535/175831039-57636b77-8e9e-4abb-9248-7c8a4874187c.png">

Bug Error inside Alfred:

`ERROR: Bluetooth Connector[Script Filter] Code 1: xcrun: error: unable to load libxcrun (dlopen(/Library/Developer/CommandLineTools/usr/lib/libxcrun.dylib, 0x0005): tried: '/Library/Developer/CommandLineTools/usr/lib/libxcrun.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))).`

**Comment by tilmanginzel** [comment]
Hey @austschn, hm interesting, have you done any OS update before it stopped working? Or has it just stopped working randomly?

The error seems to be related to MacOS CommandLineTools, what happens when you try to (re)install them via `xcode-select --install`?

**Comment by austschn** [comment]
Hey @tilmanginzel - thank you for your help. That command itself did not work, but deleting the xCode app and reinstalling it from the app store seemed to work. I didn't think you would need xCode even installed for the app to work. 

In any case, it is back online! Thank you again,

**Comment by tilmanginzel** [comment]
Glad to hear it's working again! :) 

I am not 100% sure why xcode is required, but I think that `python3` does not come preinstalled on new MacOS versions since 12.3, and it is only installed together with `xcode`. In any case, I will close the issue. If it reoccurs, freel free to reopen or create a new one!
