### ISSUE TITLE
Unable to connect to specific device

### ISSUE THREAD

**Issue by shukmeister** [tilmanginzel/alfred-bluetooth-workflow#35]
I am no longer able to select a specific device to connect to with this script. When I type in "blt" in Alfred, the list of bluetooth devices no longer appears. I am still able to bluetooth on, off, toggle, and restart.

I'm using Alfred 5.0.6 [2110] on Ventura 13.0.1 on a MacBook Air M2 (2022).

**Comment by tilmanginzel** [comment]
Hey @shukmeister, have you made any updates in-between or did it just stop working? Could you show the debug output when you type `blt`? You can find the debug output here:

1. Open the Alfred settings
2. Go to workflows and select _Bluetooth Connector_
3. `Cmd + D` should toggle the debugger
4. Now just type the `blt` command again and there should be some logs

I suppose/hope that there is some kind of error shown.

**Comment by shukmeister** [comment]
Hey @tilmanginzel, looks like I got an error:

[11:36:00.595] Logging Started...
[11:36:05.728] Bluetooth Connector[Script Filter] Queuing argument ''
[11:36:05.748] Bluetooth Connector[Script Filter] Script with argv '(null)' finished
[11:36:05.753] ERROR: Bluetooth Connector[Script Filter] Code 1: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

I think it broke when I updated to Alfred 5

**Comment by tilmanginzel** [comment]
Hm seems like this issue is related to XCode. Does reinstalling it fix the issue? You can paste the following in a terminal to reinstall it: `xcode-select --install`

**Comment by shukmeister** [comment]
That resolved the issue. Thanks!
